payoffMatrix: |
  C  C  C  =>  7  7  7 
  C  C  D  =>  3  3  9
  C  D  C  =>  3  9  3
  D  C  C  =>  9  3  3
  C  D  D  =>  0  5  5
  D  C  D  =>  5  0  5
  D  D  C  =>  5  5  0
  D  D  D  =>  1  1  1  

steps: 100          # iterationCount for fast or tournament
mode: Detailed      # detailed, fast, tournament
logLevel: warning   # none, info, warning, error


# available strategeis:
# NAME                PARAMS
# AlwaysCooperate
# Pavlov              threshold
# TitForTat
# Bully

strategies:
- TitForTat: {}
#- Pavlov: {threshold: 5}
- Bully: {}
- Bully: {}